<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>NTNP.Pricing.Api</RootNamespace>
    <UserSecretsId>ntnp-pricing-api</UserSecretsId>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.11" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NTNP.Pricing.Domain\NTNP.Pricing.Domain.csproj" />
    <ProjectReference Include="..\NTNP.Pricing.Application\NTNP.Pricing.Application.csproj" />
    <ProjectReference Include="..\NTNP.Pricing.Infrastructure\NTNP.Pricing.Infrastructure.csproj" />
    <ProjectReference Include="..\NTNP.Pricing.Contracts\NTNP.Pricing.Contracts.csproj" />
    <ProjectReference Include="..\NTNP.Pricing.Reporting\NTNP.Pricing.Reporting.csproj" />
  </ItemGroup>

</Project>
